services:
  - type: web
    name: myaimediamgr
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: https://myaimediamgr.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://myaimediamgr.onrender.com,https://myaimediamgr.com
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_STARTER
        sync: false
      - key: STRIPE_PRICE_PRO
        sync: false
      - key: STRIPE_PRICE_ENTERPRISE
        sync: false
      - key: STRIPE_PRO_TRIAL_PRODUCT
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: EMAIL_PROVIDER
        sync: false
      - key: EMAIL_API_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: ADMIN1_EMAIL
        sync: false
      - key: ADMIN1_PASSWORD
        sync: false
      - key: ADMIN2_EMAIL
        sync: false
      - key: ADMIN2_PASSWORD
        sync: false
      - key: ADMIN3_EMAIL
        sync: false
      - key: ADMIN3_PASSWORD
        sync: false
